services:
  # Serviço do MySQL
  - type: pserv
    name: mysql
    env: docker
    plan: free
    dockerCommand: mysqld --default-authentication-plugin=mysql_native_password
    disk:
      name: mysql
      mountPath: /var/lib/mysql
      sizeGB: 1
    envVars:
      - key: MYSQL_DATABASE
        value: db_usuario
      - key: MYSQL_USER
        value: admin
      - key: MYSQL_PASSWORD
        value: admin123
      - key: MYSQL_ROOT_PASSWORD
        value: root123

  # Serviço Web PHP
  - type: web
    name: cadastro-usuario
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    numInstances: 1
    healthCheckPath: /test_db.php
    healthCheckTimeout: 100
    domains:
      - cadastro-usuario.onrender.com
    envVars:
      - key: DB_HOST
        fromService:
          type: pserv
          name: mysql
          property: host
      - key: DB_USER
        value: admin
      - key: DB_PASSWORD
        value: admin123
      - key: DB_NAME
        value: db_usuario
      - key: DB_PORT
        value: "3306"
      - key: RENDER
        value: "true"
      - key: DISPLAY_ERRORS
        value: "1"
      - key: ERROR_REPORTING
        value: "E_ALL"
      - key: PHP_INI_SCAN_DIR
        value: "/var/www/html/config:/usr/local/etc/php/conf.d"
    disk:
      name: tmp
      mountPath: /tmp
      sizeGB: 1
