services:
  - type: web
    name: cadastro-usuario
    env: docker
    region: oregon
    plan: free
    buildCommand: docker build -t cadastro-usuario .
    startCommand: docker run -p $PORT:80 --env-file .env cadastro-usuario
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_NAME
        value: db_usuario
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_PORT
        value: "3306"
      - key: RENDER
        value: "true"
      - key: DISPLAY_ERRORS
        value: "1"
      - key: ERROR_REPORTING
        value: "E_ALL"
    healthCheckPath: /health.php
    healthCheckTimeout: 100
    autoDeploy: false

databases:
  - name: mysql_cadastro
    plan: free
    type: mysql
    region: oregon
    ipAllowList: []
