services:
  - type: web
    name: cadastro-usuario
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    numInstances: 1
    envVars:
      - key: DB_HOST
        value: containers-us-west-207.railway.app
      - key: DB_USER
        value: root
      - key: DB_PASSWORD
        value: 12345678
      - key: DB_NAME
        value: db_usuario
      - key: RENDER
        value: "true"
      - key: DISPLAY_ERRORS
        value: "1"
      - key: ERROR_REPORTING
        value: "E_ALL"
      - key: DB_PORT
        value: "3306"
