services:
  - type: web
    name: cadastro-usuario
    env: docker
    region: oregon
    plan: free
    buildCommand: docker build -t cadastro-usuario .
    startCommand: docker run -p $PORT:80 --env-file .env cadastro-usuario
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: mysql_cadastro
          property: host
      - key: DB_NAME
        fromDatabase:
          name: mysql_cadastro
          property: database
      - key: DB_USER
        fromDatabase:
          name: mysql_cadastro
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: mysql_cadastro
          property: password
      - key: DB_PORT
        fromDatabase:
          name: mysql_cadastro
          property: port
      - key: RENDER
        value: "true"
      - key: DISPLAY_ERRORS
        value: "1"
      - key: ERROR_REPORTING
        value: "E_ALL"
    healthCheckPath: /health.php
    healthCheckTimeout: 100
    autoDeploy: false

databases:
  - name: mysql_cadastro
    plan: free
    type: mysql
    region: oregon
    ipAllowList: []
